# Generated by Django 3.1.2 on 2020-10-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
