# Generated by Django 3.1.2 on 2020-10-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_auto_20201010_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='id',
            new_name='v_id',
        ),
    ]
