# Generated by Django 3.1.2 on 2020-10-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0009_auto_20201013_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='v_id',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
